# Generated by Django 4.0.2 on 2023-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('javascript', 'JavaScript'), ('htmlcss', 'HTML/CSS')], default=None, max_length=100, null=True),
        ),
    ]
