# Generated by Django 4.0.2 on 2023-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('JavaScript', 'Javascript'), ('HTML_&_CSS', 'Html Css')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('workshop_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField()),
                ('current_mentor_num', models.IntegerField(default=0)),
                ('max_mentor_num', models.IntegerField()),
            ],
        ),
    ]
