# Generated by Django 4.0.2 on 2023-03-29 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='current_mentor_num',
        ),
        migrations.CreateModel(
            name='WorkshopSignups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_mentor_num', to=settings.AUTH_USER_MODEL)),
                ('workshops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_mentor_num', to='workshops.workshop')),
            ],
            options={
                'unique_together': {('workshops', 'mentor')},
            },
        ),
    ]
