# Generated by Django 4.0.2 on 2023-03-30 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='current_mentor_num',
        ),
        migrations.AddField(
            model_name='workshop',
            name='current_mentor_num',
            field=models.ManyToManyField(related_name='mentor_counter', to=settings.AUTH_USER_MODEL),
        ),
    ]
