# Generated by Django 4.0.2 on 2023-03-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='skills',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('javascript', 'JavaScript'), ('htmlcss', 'HTML/CSS')], default=None, max_length=100, null=True),
        ),
    ]
