# Generated by Django 4.0.2 on 2023-03-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='owner',
        ),
    ]
