# Generated by Django 4.0.2 on 2023-03-25 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0002_alter_workshop_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
