# Generated by Django 4.0.2 on 2023-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='current_mentor_num',
            field=models.IntegerField(default=0),
        ),
    ]
