# Generated by Django 4.0.2 on 2023-03-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_current_mentor_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='skills',
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_django_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_htmlcss_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_javascript_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_python_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_react_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
