# Generated by Django 4.0.2 on 2023-03-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_current_mentor_num_workshopsignups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkshopSignups',
        ),
    ]
