# Generated by Django 4.0.2 on 2023-03-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_current_mentor_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='current_mentor_num',
        ),
    ]
