# Generated by Django 4.0.2 on 2023-03-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_remove_workshop_current_mentor_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='mentor_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
