# Generated by Django 4.0.2 on 2023-04-03 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0005_remove_workshop_mentor_count_alter_workshop_mentors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='workshops', to=settings.AUTH_USER_MODEL),
        ),
    ]
