# Generated by Django 4.0.2 on 2023-03-27 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0005_workshop_mentor_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='mentor_num',
            new_name='current_mentor_num',
        ),
        migrations.AddField(
            model_name='workshop',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
